# Generated by Django 3.1.6 on 2021-08-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=20, null=True)),
                ('volume_dispensed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('complete_status', models.BooleanField(default=False)),
            ],
        ),
    ]
